// Dados fictícios — usados apenas para visualizar as telas.
// Quando o Supabase for conectado, estes dados serão substituídos
// por consultas reais ao banco.

export const usuarioAtual = {
  nome: "Cristian",
  cargo: "Vendedor",
  empresa: "LF Lareiras",
  avatarIniciais: "CR",
  execucaoHoje: 82,
  notificacoes: 3,
};

export const atividadesRecentes = [
  { titulo: "Visita realizada", contexto: "Construtora Planum", quando: "Há 2h" },
  { titulo: "Novo relacionamento", contexto: "Arq. Beatriz Martins", quando: "Há 3h" },
  { titulo: "Proposta enviada", contexto: "Residencial Vale dos Vinhedos", quando: "Há 5h" },
];

// Compromissos da semana — gerados a partir de atividades registradas
// (campo "Próximo passo" + "Quando"), reuniões e visitas agendadas.
function diaRelativo(offset: number) {
  const d = new Date();
  d.setDate(d.getDate() + offset);
  return d.toISOString().slice(0, 10); // YYYY-MM-DD
}

export const oportunidades = [
  {
    id: "o1",
    empresa: "LF Lareiras",
    cliente: "Construtora Planum",
    produto: "Lareiras a pellet — 6 unidades",
    valor: 420000,
    etapa: "Prospecção" as const,
    probabilidade: "Média" as const,
    diasParado: 4,
  },
  {
    id: "o2",
    empresa: "LF Lareiras",
    cliente: "Arq. Rafael Lima",
    produto: "Lareira suspensa — Residencial Vale dos Vinhedos",
    valor: 168000,
    etapa: "Prospecção" as const,
    probabilidade: "Alta" as const,
    diasParado: 2,
  },
  {
    id: "o3",
    empresa: "LF Lareiras",
    cliente: "Carlos Pedroso",
    produto: "Lareira a lenha — residência",
    valor: 42000,
    etapa: "Prospecção" as const,
    probabilidade: "Baixa" as const,
    diasParado: 9,
  },
  {
    id: "o4",
    empresa: "A&G Aquecimento",
    cliente: "Construtora Alpha",
    produto: "Kit aquecimento — 12 unidades",
    valor: 310000,
    etapa: "Apresentação" as const,
    probabilidade: "Média" as const,
    diasParado: 6,
  },
  {
    id: "o5",
    empresa: "A&G Aquecimento",
    cliente: "Arq. Juliana Basso",
    produto: "Lareira Living 120",
    valor: 96000,
    etapa: "Apresentação" as const,
    probabilidade: "Alta" as const,
    diasParado: 1,
  },
  {
    id: "o6",
    empresa: "A&G Aquecimento",
    cliente: "Infinity Residence",
    produto: "Lareira embutida + instalação",
    valor: 128000,
    etapa: "Proposta" as const,
    probabilidade: "Alta" as const,
    diasParado: 3,
  },
  {
    id: "o7",
    empresa: "Sole Aquecimento",
    cliente: "Construtora Base Inc.",
    produto: "Projeto Corporate Tower — fase 1",
    valor: 580000,
    etapa: "Proposta" as const,
    probabilidade: "Média" as const,
    diasParado: 11,
  },
  {
    id: "o8",
    empresa: "LF Lareiras",
    cliente: "João Arquitetura",
    produto: "Lareira dupla face — showroom",
    valor: 210000,
    etapa: "Negociação" as const,
    probabilidade: "Alta" as const,
    diasParado: 5,
  },
  {
    id: "o9",
    empresa: "LF Lareiras",
    cliente: "Residencial Vale dos Vinhedos",
    produto: "Pacote completo — 4 unidades",
    valor: 168000,
    etapa: "Fechados" as const,
    probabilidade: "Alta" as const,
    diasParado: 2,
  },
];

export const vendasFechadas = [
  {
    id: "s1",
    cliente: "Residencial Vale dos Vinhedos",
    produto: "Pacote completo — 4 unidades",
    valor: 168000,
    empresa: "LF Lareiras",
    formaPagamento: "Financiamento",
    origem: "Arquiteto",
    data: diaRelativo(0),
  },
  {
    id: "s2",
    cliente: "Construtora Planum",
    produto: "Lareira a pellet — showroom",
    valor: 62000,
    empresa: "LF Lareiras",
    formaPagamento: "À vista",
    origem: "Indicação",
    data: diaRelativo(-1),
  },
  {
    id: "s3",
    cliente: "Carlos Pedroso",
    produto: "Lareira a lenha residencial",
    valor: 42000,
    empresa: "LF Lareiras",
    formaPagamento: "Cartão",
    origem: "Instagram",
    data: diaRelativo(-2),
  },
  {
    id: "s4",
    cliente: "Arq. Juliana Basso",
    produto: "Lareira Living 120",
    valor: 96000,
    empresa: "A&G Aquecimento",
    formaPagamento: "Boleto",
    origem: "Arquiteto",
    data: diaRelativo(-4),
  },
  {
    id: "s5",
    cliente: "Infinity Residence",
    produto: "Lareira embutida + instalação",
    valor: 128000,
    empresa: "Sole Aquecimento",
    formaPagamento: "Financiamento",
    origem: "Google",
    data: diaRelativo(-6),
  },
  {
    id: "s6",
    cliente: "João Arquitetura",
    produto: "Lareira dupla face — showroom",
    valor: 210000,
    empresa: "LF Lareiras",
    formaPagamento: "À vista",
    origem: "Cliente antigo",
    data: diaRelativo(-9),
  },
];

export const relacionamentos = [
  {
    id: "1",
    empresa: "LF Lareiras",
    nome: "João Arquitetura",
    categoria: "Arquiteto" as const,
    cidade: "Bento Gonçalves",
    telefone: "(54) 99123-4567",
    instagram: "@joaoarquitetura",
    influencia: 5,
    potencial: 4,
    indiceRelacionamento: 97,
    statusSelo: "AURA GOLD",
    temperatura: "quente" as const,
    ultimoContato: "15 dias",
    proximoContato: "em 12 dias",
    obrasIndicadas: 12,
    valorGerado: 1840000,
    observacao: "Sempre responde WhatsApp. Prefere visitas pela manhã. Gosta de material técnico em PDF.",
  },
  {
    id: "2",
    empresa: "LF Lareiras",
    nome: "Arq. Rafael Lima",
    categoria: "Arquiteto" as const,
    cidade: "Garibaldi",
    telefone: "(54) 99234-5678",
    instagram: "@rafalima.arq",
    influencia: 4,
    potencial: 4,
    indiceRelacionamento: 88,
    statusSelo: null,
    temperatura: "quente" as const,
    ultimoContato: "3 dias",
    proximoContato: "em 27 dias",
    obrasIndicadas: 6,
    valorGerado: 720000,
    observacao: "Projetos de alto padrão. Costuma responder por e-mail.",
  },
  {
    id: "3",
    empresa: "A&G Aquecimento",
    nome: "Arq. Juliana Basso",
    categoria: "Arquiteto" as const,
    cidade: "Caxias do Sul",
    telefone: "(54) 99345-6789",
    instagram: "@julianabasso",
    influencia: 3,
    potencial: 5,
    indiceRelacionamento: 74,
    statusSelo: null,
    temperatura: "ativo" as const,
    ultimoContato: "14 dias",
    proximoContato: "hoje",
    obrasIndicadas: 3,
    valorGerado: 310000,
    observacao: "Follow-up pendente sobre a Lareira Living 120.",
  },
  {
    id: "4",
    empresa: "LF Lareiras",
    nome: "Arq. Mariana Costa",
    categoria: "Arquiteto" as const,
    cidade: "Farroupilha",
    telefone: "(54) 99456-7890",
    instagram: "@marianacosta.arq",
    influencia: 2,
    potencial: 3,
    indiceRelacionamento: 51,
    statusSelo: null,
    temperatura: "esfriando" as const,
    ultimoContato: "38 dias",
    proximoContato: "atrasado",
    obrasIndicadas: 1,
    valorGerado: 95000,
    observacao: "Sem contato recente. Follow-up da Lareira Suspensa está atrasado.",
  },
  {
    id: "5",
    empresa: "LF Lareiras",
    nome: "Construtora Planum",
    categoria: "Construtora" as const,
    cidade: "Bento Gonçalves",
    telefone: "(54) 3221-0044",
    instagram: "@construtoraplanum",
    influencia: 5,
    potencial: 5,
    indiceRelacionamento: 91,
    statusSelo: "AURA GOLD",
    temperatura: "quente" as const,
    ultimoContato: "2 dias",
    proximoContato: "em 13 dias",
    obrasIndicadas: 9,
    valorGerado: 2650000,
    observacao: "Múltiplas obras em andamento. Prioridade estratégica.",
  },
  {
    id: "6",
    empresa: "Sole Aquecimento",
    nome: "Construtora Base Inc.",
    categoria: "Construtora" as const,
    cidade: "Caxias do Sul",
    telefone: "(54) 3229-5511",
    instagram: "@construtorabase",
    influencia: 3,
    potencial: 4,
    indiceRelacionamento: 68,
    statusSelo: null,
    temperatura: "ativo" as const,
    ultimoContato: "6 dias",
    proximoContato: "hoje",
    obrasIndicadas: 4,
    valorGerado: 580000,
    observacao: "Projeto Corporate Tower em fase de orçamento.",
  },
  {
    id: "7",
    empresa: "A&G Aquecimento",
    nome: "Construtora Alpha",
    categoria: "Construtora" as const,
    cidade: "Garibaldi",
    telefone: "(54) 3222-8890",
    instagram: "@construtora.alpha",
    influencia: 4,
    potencial: 3,
    indiceRelacionamento: 79,
    statusSelo: null,
    temperatura: "ativo" as const,
    ultimoContato: "9 dias",
    proximoContato: "em 6 dias",
    obrasIndicadas: 5,
    valorGerado: 890000,
    observacao: "Boa relação, retorna rápido.",
  },
  {
    id: "8",
    empresa: "LF Lareiras",
    nome: "Carlos Pedroso",
    categoria: "Cliente" as const,
    cidade: "Bento Gonçalves",
    telefone: "(54) 99567-8901",
    instagram: null,
    influencia: null,
    potencial: null,
    indiceRelacionamento: null,
    statusSelo: null,
    temperatura: "ativo" as const,
    ultimoContato: "1 dia",
    proximoContato: "aguardando orçamento",
    obrasIndicadas: 2,
    valorGerado: 42000,
    observacao: "Cliente indicador — já trouxe 2 amigos.",
    statusRelacionamento: "Cliente Indicador" as const,
  },
  {
    id: "9",
    empresa: "LF Lareiras",
    nome: "Residencial Vale dos Vinhedos",
    categoria: "Obra" as const,
    cidade: "Bento Gonçalves",
    telefone: null,
    instagram: null,
    influencia: null,
    potencial: null,
    indiceRelacionamento: null,
    statusSelo: null,
    temperatura: "quente" as const,
    ultimoContato: "hoje",
    proximoContato: "reunião agendada",
    obrasIndicadas: 0,
    valorGerado: 168000,
    observacao: "Obra em acompanhamento com Arq. Rafael Lima.",
  },
  {
    id: "10",
    empresa: "A&G Aquecimento",
    nome: "Infinity Residence",
    categoria: "Obra" as const,
    cidade: "Garibaldi",
    telefone: null,
    instagram: null,
    influencia: null,
    potencial: null,
    indiceRelacionamento: null,
    statusSelo: null,
    temperatura: "ativo" as const,
    ultimoContato: "hoje",
    proximoContato: "visita agendada",
    obrasIndicadas: 0,
    valorGerado: 96000,
    observacao: "Acompanhamento de instalação.",
  },
];
